### ISSUE TITLE
add the neovim label on luarocks.org

### ISSUE THREAD

**Issue by teto** [Tastyep/structlog.nvim#3]
I've seen your upload on luarocks.org and ofund it pretty cool. 
Just wanted to mention you may want to add the neovim label to it so it appears on https://luarocks.org/labels/neovim.
In theory the labels should be loaded from the rockspec but I had to add it manually.

**Comment by Tastyep** [comment]
Hello,

Thank you for the suggestion, I added the tag.
Adding tags using the rockspec file proved difficult for reasons I don't comprehend.
When using the website, it always complained about changing the version while it was already done. Anyway, using the CLI fixed the issue.
